-- AlterTable
ALTER TABLE "User" ADD COLUMN "aiAskUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "aiTrustUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "aiHealthUsed" BOOLEAN NOT NULL DEFAULT false;
